import {
  IconCamera,
  IconChat,
  IconEnvelope,
  IconHeart,
  IconHeartFilled,
  IconMoon,
  IconMusic,
  IconNote,
  IconPetal,
  IconSnowHeart,
  IconButterfly,
  IconSparkle,
  IconStar,
} from './icons'
import { ReactNode } from 'react'
import { FeatureKey, HM_CONFIG, Room } from './useHomeMode'

export interface RoomBtn {
  id: string
  x: number
  y: number
  color: string
  light: string
  shadow: string
  label: string
  icon: ReactNode
  floatAmp: number
  floatDur: number
  floatDelay: number
  /** action on click */
  action:
    | { kind: 'popup'; photoKey: keyof typeof HM_CONFIG.photos }
    | { kind: 'feature'; feature: FeatureKey }
}

export const ROOM_BUTTONS: Record<Room, RoomBtn[]> = {
  home: [
    {
      id: 'home-note',
      x: 20,
      y: 30,
      color: '#F2A4B8',
      light: '#FFD1DD',
      shadow: 'rgba(232,112,144,0.45)',
      label: 'a note',
      icon: <IconEnvelope />,
      floatAmp: 10,
      floatDur: 4,
      floatDelay: 0,
      action: { kind: 'popup', photoKey: 'home_01' },
    },
    {
      id: 'home-foryou',
      x: 75,
      y: 25,
      color: '#C4B0E8',
      light: '#E5D8FF',
      shadow: 'rgba(160,130,210,0.4)',
      label: 'for you',
      icon: <IconStar />,
      floatAmp: 12,
      floatDur: 4.6,
      floatDelay: 0.4,
      action: { kind: 'popup', photoKey: 'home_02' },
    },
    {
      id: 'home-particle',
      x: 50,
      y: 48,
      color: '#E07090',
      light: '#FFA8C0',
      shadow: 'rgba(224,112,144,0.5)',
      label: 'particle heart',
      icon: <IconHeart />,
      floatAmp: 9,
      floatDur: 3.4,
      floatDelay: 0.2,
      action: { kind: 'feature', feature: 'particle-heart' },
    },
    {
      id: 'home-wish',
      x: 18,
      y: 70,
      color: '#E8C860',
      light: '#FFE89A',
      shadow: 'rgba(224,200,96,0.45)',
      label: 'make a wish',
      icon: <IconSparkle />,
      floatAmp: 13,
      floatDur: 5,
      floatDelay: 0.8,
      action: { kind: 'feature', feature: 'fireworks' },
    },
    {
      id: 'home-song',
      x: 78,
      y: 65,
      color: '#8B7EC8',
      light: '#B7AAEC',
      shadow: 'rgba(139,126,200,0.45)',
      label: 'our song',
      icon: <IconMusic />,
      floatAmp: 11,
      floatDur: 4.2,
      floatDelay: 1.2,
      action: { kind: 'feature', feature: 'crystal-heart' },
    },
  ],
  kitchen: [
    {
      id: 'k-remember',
      x: 22,
      y: 28,
      color: '#F0B090',
      light: '#FFD4BC',
      shadow: 'rgba(240,176,144,0.45)',
      label: 'remember this?',
      icon: <IconCamera />,
      floatAmp: 10,
      floatDur: 4,
      floatDelay: 0,
      action: { kind: 'popup', photoKey: 'kitchen_01' },
    },
    {
      id: 'k-check',
      x: 72,
      y: 30,
      color: '#E8A050',
      light: '#FFC68A',
      shadow: 'rgba(232,160,80,0.45)',
      label: 'just checking',
      icon: <IconChat />,
      floatAmp: 12,
      floatDur: 4.4,
      floatDelay: 0.5,
      action: { kind: 'popup', photoKey: 'kitchen_02' },
    },
    {
      id: 'k-pulse',
      x: 48,
      y: 50,
      color: '#E87090',
      light: '#FFA8C0',
      shadow: 'rgba(232,112,144,0.5)',
      label: 'feel this',
      icon: <IconHeartFilled />,
      floatAmp: 9,
      floatDur: 3.6,
      floatDelay: 0.3,
      action: { kind: 'feature', feature: 'canvas-pulse' },
    },
    {
      id: 'k-bloom',
      x: 20,
      y: 68,
      color: '#7EC890',
      light: '#B5ECC1',
      shadow: 'rgba(126,200,144,0.45)',
      label: 'watch this',
      icon: <IconPetal />,
      floatAmp: 13,
      floatDur: 4.8,
      floatDelay: 0.9,
      action: { kind: 'feature', feature: 'flower-bloom' },
    },
    {
      id: 'k-magic',
      x: 75,
      y: 70,
      color: '#90C4E8',
      light: '#BCE0FF',
      shadow: 'rgba(144,196,232,0.45)',
      label: 'touch it',
      icon: <IconSnowHeart />,
      floatAmp: 11,
      floatDur: 4.2,
      floatDelay: 1.3,
      action: { kind: 'feature', feature: 'falling-hearts' },
    },
  ],
  garden: [
    {
      id: 'g-justbecause',
      x: 20,
      y: 30,
      color: '#F0A0C0',
      light: '#FFCAE0',
      shadow: 'rgba(240,160,192,0.45)',
      label: 'just because',
      icon: <IconNote />,
      floatAmp: 10,
      floatDur: 4,
      floatDelay: 0,
      action: { kind: 'popup', photoKey: 'garden_01' },
    },
    {
      id: 'g-iseeyou',
      x: 74,
      y: 32,
      color: '#88C490',
      light: '#BBE6C2',
      shadow: 'rgba(136,196,144,0.45)',
      label: 'i see you',
      icon: <IconPetal />,
      floatAmp: 12,
      floatDur: 4.4,
      floatDelay: 0.5,
      action: { kind: 'popup', photoKey: 'garden_02' },
    },
    {
      id: 'g-stardust',
      x: 50,
      y: 48,
      color: '#E8C860',
      light: '#FFE89A',
      shadow: 'rgba(232,200,96,0.45)',
      label: 'touch the sky',
      icon: <IconSparkle />,
      floatAmp: 9,
      floatDur: 3.6,
      floatDelay: 0.3,
      action: { kind: 'feature', feature: 'particle-field' },
    },
    {
      id: 'g-wander',
      x: 18,
      y: 68,
      color: '#C0A8E8',
      light: '#DCC9FF',
      shadow: 'rgba(192,168,232,0.45)',
      label: 'follow me',
      icon: <IconButterfly />,
      floatAmp: 13,
      floatDur: 4.8,
      floatDelay: 0.9,
      action: { kind: 'feature', feature: 'butterfly-parallax' },
    },
    {
      id: 'g-night',
      x: 76,
      y: 67,
      color: '#5060C0',
      light: '#8090E0',
      shadow: 'rgba(80,96,192,0.5)',
      label: 'look up',
      icon: <IconMoon />,
      floatAmp: 11,
      floatDur: 4.2,
      floatDelay: 1.3,
      action: { kind: 'feature', feature: 'night-sky' },
    },
  ],
}
